<a href="https://colab.research.google.com/github/Ram6023/python-practice/blob/main/23_01_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# import libraries
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('logistic_regression_dataset 2.csv')

In [5]:
df.head()

   age  salary  experience  loan_amount  approved
0   56   34382          15       319286         0
1   46  104291           7        61307         1
2   32   23756          20       140565         0
3   25   40609           0       260095         0
4   38   36478           7       317229         0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          1000 non-null   int64
 1   salary       1000 non-null   int64
 2   experience   1000 non-null   int64
 3   loan_amount  1000 non-null   int64
 4   approved     1000 non-null   int64
dtypes: int64(5)
memory usage: 39.2 KB

In [8]:
df.describe()

               age         salary   experience    loan_amount     approved
count  1000.000000    1000.000000  1000.000000    1000.000000  1000.000000
mean     38.745000   69785.694000    19.359000  253712.375000     0.377000
std      12.186734   28440.126145    11.388055  140652.856271     0.484877
min      18.000000   20060.000000     0.000000    5138.000000     0.000000
25%      28.000000   46114.500000     9.000000  139118.750000     0.000000
50%      40.000000   69210.500000    20.000000  248201.000000     0.000000
75%      50.000000   95215.500000    29.000000  368059.250000     1.000000
max      59.000000  119986.000000    39.000000  499178.000000     1.000000

In [9]:
#check missing values
df.isnull().sum()

age            0
salary         0
experience     0
loan_amount    0
approved       0
dtype: int64

In [10]:
# divide into x and y
x= df.drop("approved",axis=1)
y= df["approved"]

In [11]:
# split the data into train and test
from sklearn.model_selection import train_test_split

In [12]:
x

     age  salary  experience  loan_amount
0     56   34382          15       319286
1     46  104291           7        61307
2     32   23756          20       140565
3     25   40609           0       260095
4     38   36478           7       317229
..   ...     ...         ...          ...
995   41   32115          19       225460
996   32   59062           6       495834
997   46   42911          13       486546
998   25   52556           8       374100
999   22   98131          18       385596

[1000 rows x 4 columns]

In [13]:
y

0      0
1      1
2      0
3      0
4      0
      ..
995    0
996    0
997    0
998    0
999    0
Name: approved, Length: 1000, dtype: int64

In [15]:
#train the model
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

#load the model
model = LogisticRegression()
# fit the model
train_model=model.fit(x_train, y_train)
#make predictions
y_pred=train_model.predict(x_test)
y_pred

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1])

In [17]:
# check loss function
from sklearn.metrics import log_loss
logloss= log_loss(y_test, y_pred)
print("logloss of logistic regression model is:",logloss)

logloss of logistic regression model is: 6.127421076149916

In [19]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)
cm

array([[115,  13],
       [ 21,  51]])

In [20]:
# Calculate accuracy
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of the logistic regression model is: {accuracy:.4f}")

Accuracy of the logistic regression model is: 0.8300